apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-ps-alertmanager-trigger-vmcreate
  labels:
    app: veba-ui
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.event.router/event
      subject: VmCreatedEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-ps-alertmanager
